name: business
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.6
  custom_date_range_picker: ^1.0.10
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_swipe_action_cell: ^3.1.3
  get_it: ^7.6.7
  intl: ^0.18.1
  lottie: ^3.1.0
  sqflite: ^2.3.2
  uuid: ^4.3.3
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

